### ISSUE TITLE
Missing 6.3.0 release tag

### ISSUE THREAD

**Issue by perestoronin** [RadeonOpenCompute/ROCT-Thunk-Interface#110]
Missing 6.3.0 release tag

**Comment by kentrussell** [comment]
Looks like the README update didn't make it in here. I'll get on that now. As of ROCm 6.3, this repo has been merged into ROCR-Runtime. You can find the code at https://github.com/ROCm/ROCR-Runtime/tree/amd-staging/libhsakmt
