### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by jamborm** [RadeonOpenCompute/ROCT-Thunk-Interface#2]
Can you please clarify the license under which files in this repository can be distributed?  It is important for inclusion in package repositories that do not belong to AMD.

**Comment by johnbridgman** [comment]
Hi Martin,

The thunk code is licensed under standard X11 (sometimes called MIT) license. The intent is to have common licensing with the rest of the open source graphics stack, which is all X11 with the exception of a few GPL-licensed files in the drm core.

**Comment by devurandom** [comment]
A license file would be great.

**Comment by gstoner** [comment]
Licence information has been updated
