### ISSUE TITLE
Can't install headers without building a distro package

### ISSUE THREAD

**Issue by jvesely** [RadeonOpenCompute/ROCT-Thunk-Interface#20]
Standard build only installs:
libhsakmt/lib/libhsakmt.so.1.0.6
libhsakmt/lib/libhsakmt.so.1
libhsakmt/lib/libhsakmt.so

build-dev/install-dev tries to build an rpm package.
Is there a reason the ability to install headers was removed?

**Comment by fxkamd** [comment]
You can always copy the headers manually, if that's what you really want. But from a support and system maintenance perspective, installing a distribution package is much cleaner.

**Comment by jvesely** [comment]
Why wouldn't I want to install headers when installing a source build library? The same argument applies when installing the .so files. It used to work OK, and most projects work that way. Was there a specific reason to change this?

It's cleaner to install headers using cmake/make than copying by hand; it gets recorded in install manifest.
would it be acceptable to hide header installation behind a new target?

**Comment by fxkamd** [comment]
I think this is probably related to how headers are split into a separate package. We had to jump through some hoops to get CMake to build two separate packages. The header files are described in hsakmt-dev.txt as opposed to CMakeLists.txt. There are custom targets for package-dev and install-dev. If I understand it correctly you should be able to install the headers with "make install-dev".

**Comment by jvesely** [comment]
yes, and there's the problem. install-dev depends on build-dev, which tries to build a package. I don't think the local installation of headers should require that.

**Comment by jvesely** [comment]
yes, the patch fixes `make install-dev`, and enables me to install headers without building an rpm/deb package.
Thank you.

**Comment by jvesely** [comment]
hi, will the patch be included in future (stable) releases?

**Comment by jvesely** [comment]
Ping. It does not look like this made it to 1.8.

**Comment by fxkamd** [comment]
Right. 1.9 will see some improvements in the build system. Well, changes anyway, I hope they'll add up to improvements. ;)

**Comment by kentrussell** [comment]
Can you try the 1.9 release and see if the issue persists?

**Comment by jvesely** [comment]
Hi,
sorry for the delay. The 1.9.x branch installs headers without asking for packaging tool first.
Now, if you could remove that "-Werror" monstrosity (and stop re-adding it), things would be shiny.

thanks,
Jan

**Comment by jvesely** [comment]
anyway. this issue is fixed. Thanks.
