### ISSUE TITLE
Compatibility with mainline kernel 4.17?

### ISSUE THREAD

**Issue by justxi** [RadeonOpenCompute/ROCT-Thunk-Interface#21]
The current version of ROCm (1.8) seems to depend on the kernel sources 4.13 (ROCK-Kernel-Driver).
Will there come an update once the new mainline kernel (4.17) is release or will it be compatible?

**Comment by fxkamd** [comment]
ROCm 1.8 is not compatible with kernels newer than 4.13. There will no ROCm 1.8-based release with support for newer kernels. Newer kernels will only be supported with future ROCm releases (1.9 etc).

**Comment by justxi** [comment]
Ok, thanks for the information.
