### ISSUE TITLE
Segfault @ fmm.c:231 NON_VALID_GPU_ID 

### ISSUE THREAD

**Issue by Dekken** [RadeonOpenCompute/ROCT-Thunk-Interface#23]
Segfaults from repo too but had to build from source to get symbols

```
Starting program: /path/to/tmp/rocm/test/saxpy
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff65fffac in find_first_dgpu (gpu_id=0x7fffffffd4b8) at /path/to/tmp/rocm/thunk/src/fmm.c:231
231                     if (gpu_mem[i].gpu_id == NON_VALID_GPU_ID)
(gdb) bt
#0  0x00007ffff65fffac in find_first_dgpu (gpu_id=0x7fffffffd4b8) at /path/to/tmp/rocm/thunk/src/fmm.c:231
```

**Comment by Dekken** [comment]
```
/opt/rocm/bin/rocm-smi


====================    ROCm System Management Interface    ====================
================================================================================
 GPU  Temp    AvgPwr   SCLK     MCLK     Fan      Perf    SCLK OD
  1   30.0c   7.0W     852Mhz   167Mhz   0.0%     auto      0%
  0   31.0c   3.0W     852Mhz   500Mhz   0.0%     auto      0%
================================================================================
====================           End of ROCm SMI Log          ====================
```

**Comment by Dekken** [comment]
/opt/rocm/hsa/sampl/vector_copy segfaults too

**Comment by fxkamd** [comment]
Hmm, I can see an overflow bug because a loop has the wrong termination condition. But it shouldn't overflow in the first place. It looks like KFD hasn't initialized any dGPUs on your system. Please show me a full kernel log and /sys/class/kfd/kfd/topology/nodes/*/properties.

**Comment by Dekken** [comment]
[here](https://gist.github.com/Dekken/b5f7b6a8b55b4bc470fe6fad3fbd50e5)

**Comment by fxkamd** [comment]
Hmm, KFD is fine.

I think I've seen similar segfaults caused by permission problems when the Thunk couldn't open /dev/dri/renderD* render nodes. Normally the permissions are managed by udevd for local users. If you're logging in remotely make sure that your user account is in the video group.

**Comment by Dekken** [comment]
I am logging in remotely - let me test on the device itself

**Comment by Dekken** [comment]
physical access works for the same user, but doesn't seem to even when the same user is added to the video group and ssh-ed in

**Comment by Dekken** [comment]
Ok super strange - it now works for the same remote user, after an initial run as physical

**Comment by fxkamd** [comment]
Are you still logged in locally? As long as you're logged in, that user will be on the access control list. I think when you log out the user should get removed.

What are the permissions of /dev/dri/*?

ls -l /dev/dri/*
getfacl /dev/dri/*

**Comment by Dekken** [comment]
the user is no longer logged in locally - and I rebooted just to be sure

```
ls -l /dev/dri/*
crw-rw---- 1 root video 226,   0 Jul  5 22:09 /dev/dri/card0
crw-rw---- 1 root video 226,   1 Jul  5 22:09 /dev/dri/card1
crw-rw---- 1 root video 226, 128 Jul  5 22:09 /dev/dri/renderD128
crw-rw---- 1 root video 226, 129 Jul  5 22:09 /dev/dri/renderD129
philix@stryk:~$ getfacl /dev/dri/*
getfacl: Removing leading '/' from absolute path names
# file: dev/dri/card0
# owner: root
# group: video
user::rw-
group::rw-
other::---

# file: dev/dri/card1
# owner: root
# group: video
user::rw-
group::rw-
other::---

# file: dev/dri/renderD128
# owner: root
# group: video
user::rw-
group::rw-
other::---

# file: dev/dri/renderD129
# owner: root
# group: video
user::rw-
group::rw-
other::---

```

everything still works with remote user

**Comment by fxkamd** [comment]
If you just added your account to the video group, that change didn't take effect for the current login. Logging out and back in would have registered the new group membership.

**Comment by Dekken** [comment]
that makes sense - is there possibly some method to confer this information to the user in future?

**Comment by Dekken** [comment]
I know the setup says to add yourself to the user group, but I used to be able to do things locally without having to bother

**Comment by Dekken** [comment]
Thanks for your time @fxkamd
