### ISSUE TITLE
Compiling from git and release results in different library versions

### ISSUE THREAD

**Issue by justxi** [RadeonOpenCompute/ROCT-Thunk-Interface#26]
Hi,

when I checkout the source with "git clone -b roc-2.0.x ...", run cmake and make the "libhsakmt.so" gets the version "2.0.0". When I download the source file (tar.gz) from the releases, the library gets the version "1.0.0". If I understand it right, the version is determined from the git repository information, which are not available in the source file and therefore the default version string "1.0.0" is taken.
A simple solution could be to change the line

https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/blob/3ba20ce921ec9dce711f3812ef1ed8e859f16d96/CMakeLists.txt#L45

to contain "2.0.0".

**Comment by fxkamd** [comment]
We're going to fix this and stop getting the version from the repository. It's messed up with our internal repositories too, because they're missing the release tags. We're going to start bumping the versions manually to indicate feature changes so the version number will actually be meaningful.
