### ISSUE TITLE
Unnecessary SOVERSION bump

### ISSUE THREAD

**Issue by sclarkson** [RadeonOpenCompute/ROCT-Thunk-Interface#27]
Tagging the repository as 2.0.0 has cause the library to build as libhsakmt.so.2, despite the symbols list still being backwards compatible with previous versions (libhsakmt.so.1)

Confusingly, the symbols are still tagged as HSAKMT_1 in
https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/blob/3ba20ce921ec9dce711f3812ef1ed8e859f16d96/src/libhsakmt.ver#L1-L6

If you plan to keep doing shared library versioning like this, the the tag should be changed. But ideally,  the SOVERSION should be tracked separately from the release version.

**Comment by fxkamd** [comment]
I agree. We're going to fix that by separating the SO version from the release tag.

**Comment by sclarkson** [comment]
Are you planning on keeping it libhsakmt.so.1, then?

**Comment by jlgreathouse** [comment]
Yes, the current version should be `libhsakmt.so.1`, which is also what we currently package based on builds from our AMD-internal repo mirrors.

**Comment by tstellar** [comment]
I've created a pull request for this: https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/pull/29

**Comment by kentrussell** [comment]
This will be fixed in 2.5

**Comment by kentrussell** [comment]
Fixed in 2.5 thanks to @tstellar
