### ISSUE TITLE
GPUOpen website links to outdated branch

### ISSUE THREAD

**Issue by devurandom** [RadeonOpenCompute/ROCT-Thunk-Interface#3]
The [GPUOpen website](http://gpuopen.com/compute-product/rocm/) links to the outdated dev branch of this repository, which is significantly behind master.

The same seems to be true for the ROCR-Runtime and the ROCK-Kernel-Driver.

**Comment by gstoner** [comment]
Closed update GPU Open main landing page for ROCm,   Blog Post we not edited
