### ISSUE TITLE
/dev/kfd has the wrong permissions

### ISSUE THREAD

**Issue by hameerabbasi** [RadeonOpenCompute/ROCT-Thunk-Interface#36]
(Please feel free to transfer this issue if this is the wrong place to put it)

Hi, my `/dev/kfd` device has the wrong permissions, which means that ROCm only runs for root.

```bash
$ ls -la /dev | grep kfd
crw-------   1 root    root    234,   0 Mai 21 05:13 kfd
```

I'm on Ubuntu 19.04 using the Xenial packages modified according to this: https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm#option-4-install-directly-on-host

**Comment by fxkamd** [comment]
/dev/kfd permissions are controlled by udevd. You'll need to install a udev configuration file in /etc/udev/rules.d to set the permissions correctly. Don't forget to update your initramfs after creating the config file. This line should do the trick to set the permissions the same way most distros set up the DRM render nodes in /dev/dri/renderD*:

KERNEL=="kfd", MODE="0660", GROUP="video", TAG+="uaccess"

**Comment by hameerabbasi** [comment]
I did this, and it worked -- thanks. But shouldn't the packages already do that for me?

**Comment by fxkamd** [comment]
If you use the rock-dkms package to install KFD, I think that should take care of the udev configuration.  Are you using rock-dkms? What's the output of "dkms status" and "uname -r"?

**Comment by hameerabbasi** [comment]
I'm not... I used the `rocm-dev` and `rocm-libs`, I'm using the mainline kernel driver.

**Comment by kentrussell** [comment]
The KFD permissions are set by the kernel package. Since you're using mainline kernel, you have to modify udev yourself. If you use the rock-dkms kernel package, the permissions are set automatically.
