### ISSUE TITLE
GPU (and system) locks up when running tests (run_kfdtest.sh)

### ISSUE THREAD

**Issue by shree1717** [RadeonOpenCompute/ROCT-Thunk-Interface#37]
When running run_kfdtest.sh from ROCT-Thunk-Interface, tag roc-2.6.0, from a KDE konsole under plasmashell, the GPU locks up, taking all tasks down with it which call into amdgpu, in particular systemd.

The kernel is a vanilla Linux 5.1.16 using the in-tree amdgpu driver.

Unfortunately I don’t know which test triggered the error, and I am loathe, somewhat, to repeat the experiment.

When no X is running and kfdtest is run from the Linux console, the system does not lock up (although I only tried it once).

I have attached the kernel log with the lock up ([run_kfdtest.journalctl-1.lockup-when-run-under-plasma.kernel.txt](https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/files/3388994/run_kfdtest.journalctl-1.lockup-when-run-under-plasma.kernel.txt)), a kernel log without the lock up ([run_kfdtest.journalctl-2.completes-when-no-X-is-running.kernel.txt](https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/files/3388995/run_kfdtest.journalctl-2.completes-when-no-X-is-running.kernel.txt)), and the output of run_kfdtest.sh without the lock up ([run_kfdtest.log.txt](https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/files/3388996/run_kfdtest.log.txt)).

**Comment by johnbridgman** [comment]
Looks like the eviction tests are triggering the lockup. I'm not in front of a ROCm system so can't tell you the best way to omit the eviction tests, but that is probably the safest thing to do for now.


Entering "run_kfdtest.sh -h" should give you the command line parms. IIRC there is a text file that can also be edited to limit the tests that are run.


The eviction tests are pretty drastic - they force the system into a hard out-of-memory situation in order to trigger all the eviction logic - sounds like something in the graphics stack might be getting wedged during the test before the compute stack recovers. There have also been some recent fixes in the eviction logic IIRC.

**Comment by fxkamd** [comment]
I was just working on a memory and page table corruption bug that was triggered by our eviction test on stock kernels: https://lists.freedesktop.org/archives/amd-gfx/2019-July/036620.html. The log you posted looks familiar.

There is a combination of other issues that are conspiring to make this worse:

* GTT size limited to framebuffer size. This is to avoid OOM panic. There was a discussion about that on the mailing list a few months ago: https://lists.freedesktop.org/archives/amd-gfx/2019-April/033586.html

* Enabling retry page faults leads to fault storms that slow down the page fault handling and exposes some preemption problems in SDMA queues, which can trigger GPU resets. I guess enabling retry faults was premature, given that we're not really using them yet

**Comment by shree1717** [comment]
I have to apologize: The ROCT-Thunk-Interface I compiled was not 2.6.0 but 2.5.0 because I compiled from the master branch whose HEAD is apparently still at 2.5.0. Having only very little experience with git I didn’t notice this; I’m sorry.

Still, the driver shouldn’t lock up even with a non-up-to-date (buggy?) version of ROCT-Thunk-Interface.

**Comment by kentrussell** [comment]
It's quite alright. We have some patches to address some Eviction issues. If things are looking good in 3.1, I'll close this on the 3.2 release. If it's still present in the 3.1 release, please let us know. I believe that 3.2 should have the final Eviction cleanup, but that's mostly related to performance, not lockups

**Comment by kentrussell** [comment]
Closing due to it being resolved in 3.1. Please reopen it if you still experience an issue
