### ISSUE TITLE
Information about kernel compatibility

### ISSUE THREAD

**Issue by devurandom** [RadeonOpenCompute/ROCT-Thunk-Interface#5]
Is this libhsakmt supposed to work with amdkfd from Linux 4.7?

The [ROCK-Kernel-Driver repository](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/) states that the libhsakmt library contained therein is *not* compatible with mainline Linux:
```
##### Note regarding libhsakmt compatibility
Please note that the libhsakmt library in this repository is NOT compatible
with amdkfd that is distributed as part of the mainline Linux kernel
from 3.19 and onward.
```

Does this mean that the libhsakmt library contained herein *is* compatible with mainline Linux?

**Comment by arodrigx7** [comment]
Hi devurandom, 

The libhsakmt contained here in ROCT is not compatible with the upstream Linux kernel. 

I'll fix the confusing wording of that message in a bit when I get to my laptop.

**Comment by devurandom** [comment]
Hi Andres!

Thanks! It would probably be helpful to have the information in this repository's readme, too. And maybe the number of variants of libhsakmt repositories can be reduced to this repository here?

Further questions:
* Is there a libhsakmt somewhere that *is* compatible?
* What is the roadmap for merging the amdkfd kernel changes upstream?
* Can the patches to amdkfd be separated from non-amdkfd related parts, so I could maybe get the Gentoo kernel maintainers to merge them into sys-kernel/gentoo-sources? They would probably only agree, if the patches would affect very limited parts of the kernel, e.g. only the amdkfd driver sources.

**Comment by arodrigx7** [comment]
Hi devurandom,

I've updated the README files to be a bit clearer on this aspect. Regarding your other questions:

 > *Is there a libhsakmt somewhere that is compatible?

Yes, the current libhsakmt compatible with the upstream kernel is here: 
https://cgit.freedesktop.org/amd/hsakmt/

> *What is the roadmap for merging the amdkfd kernel changes upstream?

We are currently in the process of upstreaming our code. We don't particularly enjoy maintaining such a large fork of upstream, so this is something that is very important for us. For further details I'd keep an eye on the relevant linux mailing lists.

> *Can the patches to amdkfd be separated from non-amdkfd related parts, so I could maybe get the Gentoo kernel maintainers to merge them into sys-kernel/gentoo-sources? They would probably only agree, if the patches would affect very limited parts of the kernel, e.g. only the amdkfd driver sources.

Our patches are rebased on a specific commits from upstream. If you look using merge-parent you should be able to find it and generate a patch list.

However, amdkfd uses advanced IOMMUv2 and PCIe features that may not be available on older kernels. These subsystems may need to be updated accordingly.

As part of our upstreaming effort we will also be working with distro maintainers to get the relevant portions mixed in.

Any other questions let me know.
