### ISSUE TITLE
The kfd test case KFDMemoryTest.BigSysBufferStressTest failed to detect memory leak on my machine, but success on my another machine which is run different kernel and ubuntu version..

### ISSUE THREAD

**Issue by andyzhanged** [RadeonOpenCompute/ROCT-Thunk-Interface#57]
Hi, 
The kfdtest case KFDMemoryTest.BigSysBufferStressTest is a stress test, it can test memory leak simultaneously. So i try to make a memory leak to see if the case can detect it. My gpu is amd vega20 and thunk branch is roct-3.3, rock is also 3.3. My code is as follows show, i only add some code to make a memory leak.
```
TEST_F(KFDMemoryTest, BigSysBufferStressTest) {
    if (!is_dgpu()) {
        LOG() << "Skipping test: Running on APU fails and locks the system." << std::endl;
        return;
    }
    TEST_REQUIRE_ENV_CAPABILITIES(ENVCAPS_64BITLINUX);
    TEST_START(TESTPROFILE_RUNALL);

    HSAuint64 AlternateVAGPU;
    HsaMemMapFlags mapFlags = {0};
    int ret;

    int defaultGPUNode = m_NodeInfo.HsaDefaultGPUNode();
    ASSERT_GE(defaultGPUNode, 0) << "failed to get default GPU Node";

    /* Repeatedly allocate and map big buffers in system memory until it fails,
     * then unmap and free them.
     */
#define ARRAY_ENTRIES 2048

    int i = 0, allocationCount = 0;
    unsigned int* pDb_array[ARRAY_ENTRIES];
    HSAuint64 block_size_mb = 128;
    HSAuint64 block_size = block_size_mb * 1024 * 1024;

    /* Test 4 times to see if there is any memory leak.*/
    for (int repeat = 1; repeat < 5; repeat++) {

        for (i = 0; i < ARRAY_ENTRIES; i++) {
            ret = hsaKmtAllocMemory(0 /* system */, block_size, m_MemoryFlags,
                    reinterpret_cast<void**>(&pDb_array[i]));
            if (ret)
                break;

            /*malloc 512KB memory every loop, not free*/
            void *test = malloc(512*1024);
            if (NULL == test) {
                 printf("hygonDebug, xxxxx \n");
             } else {
               memset(test, 0, 512*1024);
             }

            ret = hsaKmtMapMemoryToGPUNodes(pDb_array[i], block_size,
                    &AlternateVAGPU, mapFlags, 1, reinterpret_cast<HSAuint32 *>(&defaultGPUNode));
            if (ret) {
                EXPECT_SUCCESS(hsaKmtFreeMemory(pDb_array[i], block_size));
                break;
            }
        }

        LOG() << "Allocated system buffers time " << std::dec << repeat << ": "
            << i << " * " << block_size_mb << "MB" << std::endl;

        if (allocationCount == 0)
            allocationCount = i;
        EXPECT_GE(i, allocationCount) << "There might be memory leak!" << std::endl;

        for (int j = 0; j < i; j++) {
            EXPECT_SUCCESS(hsaKmtUnmapMemoryToGPU(pDb_array[j]));
            EXPECT_SUCCESS(hsaKmtFreeMemory(pDb_array[j], block_size));
        }
    }
    TEST_END
}
```

My test machine info as follows:

```
root@dcu:~# uname -a
Linux dcu 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

root@dcu:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

root@dcu:~# free -m
              total        used        free      shared  buff/cache   available
Mem:          64259        2900       59551         929        1807       59797
Swap:          2047        1708         339

zhanged@dcu:~/code/umd/ROCT-Thunk-Interface/tests/kfdtest/build$  dkms status
amdgpu, 3.3-19, 5.0.0-23-generic, x86_64: installed
```
When i run the case on my machine, it cannot detect memory leak, the log  is 
```
zhanged@dcu:~/code/umd/ROCT-Thunk-Interface/tests/kfdtest/build$ ./kfdtest --gtest_filter=KFDMemoryTest.BigSysBufferStressTest
[          ] Profile: Full Test
[          ] HW capabilities: 0x9
Note: Google Test filter = KFDMemoryTest.BigSysBufferStressTest
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from KFDMemoryTest
[ RUN      ] KFDMemoryTest.BigSysBufferStressTest
[          ] Allocated system buffers time 1: 467 * 128MB
[          ] Allocated system buffers time 2: 467 * 128MB
[          ] Allocated system buffers time 3: 467 * 128MB
[          ] Allocated system buffers time 4: 467 * 128MB
[       OK ] KFDMemoryTest.BigSysBufferStressTest (80174 ms)
[----------] 1 test from KFDMemoryTest (80174 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (80174 ms total)
[  PASSED  ] 1 test.
```
The case failed to detect memory leak. I double confirm the question on my colleague’s machine which is same kernel,dirver and ubuntu version. But when i run it on my another machine with the same program, it can detect memory leak. My another machine info as follows, the kernel version is different.
```
yxl@hygon:~$
yxl@hygon:~$ uname -r
4.15.0-112-generic
yxl@hygon:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
yxl@hygon:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:          64342        4415       27200         804       32725       58490
Swap:          2047           0        2047
yxl@hygon:~$
```
So i have some questione:
1. Is there someone has some clues? Is the kernel version result in this question?
2. This test case will allocate until no memory left and task the count as a condition to decide if memory leak, i think maybe it is not reliable.

**Comment by fxkamd** [comment]
KFD has internal limits of how much memory you can allocate and map to the GPU. The reason is that all memory belonging to KFD processes must be resident while they are running on the GPU. We want to prevent memory overcommitment by KFD processes to avoid excessive evictions because our current memory manager is very bad at dealing with memory overcommitment.

Calling "malloc" does not count against the KFD-internal memory limits. Malloc'ed memory can be swapped out by the kernel easily without affecting anything on the GPU. Therefore I would not expect your change to cause a memory leak to be detected in the KFD memory allocation test. It's not clear why your two systems are behaving differently. They look quite similar in terms of memory and swap size. Your kernel log may tell you more about the failure mode.

If you changed the "malloc" to hsaKmtAllocMemory, that leak should be detected reliably.

**Comment by andyzhanged** [comment]
Hi fxkamd, thank you very much for your reply.  Memory must be resident means it can not be pageable, is that right?
As i know, there are three memory allocate mode which is userptr, gtt and vram. Userptr is the default memory allocate mode after roct-2.7. I think Userptr memory is pageable, but gtt and vram is not pageable.

**Comment by fxkamd** [comment]
Userptr memory is pageable. But we cannot execute GPU queues unless all of it is resident. The driver will attempt to find out physical addresses of all userprt memory. This will make the memory resident. Only then the user mode GPU queues can be enabled. If this fails, all user mode execution on the GPU for that process is stalled.

**Comment by andyzhanged** [comment]
Ok, i see, thank you very much.
