### ISSUE TITLE
make install doesn't install the header files

### ISSUE THREAD

**Issue by rigtorp** [RadeonOpenCompute/ROCT-Thunk-Interface#60]
First building:
```
git clone -b roc-3.6.x https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface.git
cd ROCT-Thunk-Interface
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/opt/rocm ..
make
```

Then installing:
```
sudo make install
[100%] Built target hsakmt
Install the project...
-- Install configuration: "Release"
-- Installing: /opt/rocm/lib64/libhsakmt.so.1.0.6
-- Up-to-date: /opt/rocm/lib64/libhsakmt.so.1
-- Up-to-date: /opt/rocm/lib64/libhsakmt.so
-- Up-to-date: /opt/rocm/share/doc/hsakmt/LICENSE.md
```

You can see that the header files in `include/` are not installed and have to be installed manually:
```
sudo cp -r include /opt/rocm/
```

**Comment by kentrussell** [comment]
This can be addressed with "make install-dev" as the headers are included in the dev package. I have updated the README for our next release to make this more explicitly clear, as it is not stated anywhere to do "make install-dev"

**Comment by rigtorp** [comment]
Ok, thanks. It's a bit unorthodox to have a `make install-dev`. Rpmbuild and other packaging tools can split the install into a binary and a `-devel`  package themselves.
