### ISSUE TITLE
make install doesn't install CMake export targets

### ISSUE THREAD

**Issue by rigtorp** [RadeonOpenCompute/ROCT-Thunk-Interface#61]
CMake export targets for use with `find_package` should be installed during installation.

See:
- http://cliutils.gitlab.io/modern-cmake/chapters/install/exporting.html
- https://cmake.org/cmake/help/latest/guide/tutorial/index.html#adding-export-configuration-step-11

**Comment by kentrussell** [comment]
Our CMake process for this project was overhauled and this issue was addressed. Unfortunately the overhaul missed the 3.6-Beta cutoff, but will be included in the next ROCm release.

**Comment by rigtorp** [comment]
I didn't try it, but it looks like that branch will install the CMake exports correctly.

**Comment by rigtorp** [comment]
Fixed in ROCm 3.7
