### ISSUE TITLE
How to pass args when dispatch a compute kernel using PM4 packet?

### ISSUE THREAD

**Issue by lscat11** [RadeonOpenCompute/ROCT-Thunk-Interface#63]
Hi, I have learned how to pass args to compute kernels and allocate LDS using HSA AQL packets, and I was wondering how to do this using PM4 packets. I could only dispatch the "nop" compute kernel which has no args. Are there any special registers for parameter passing?

Thanks.

**Comment by fxkamd** [comment]
KFDTest uses PM4 packets for dispatching compute jobs. We use regular VGPRs to pass parameters to our SP3 assembly shaders. This probably doesn't match the ABI for parameter passing used by AQL. I think the ABI is probably documented somewhere in the LLVM repository. For the mechanics of dispatching shaders with PM4, take a look at tests/kfdtest/src/Dispatch.cpp for an example. It's messy and complicated. There is a reason why AQL was invented. ;)
