### ISSUE TITLE
How to enable Global Data Share(GDS) segment for GFX9?

### ISSUE THREAD

**Issue by lscat11** [RadeonOpenCompute/ROCT-Thunk-Interface#64]
When I looked at the GPU's property file `/sys/devices/virtual/kfd/kfd/topology/nodes/1/properties`, I found that the gds_size_in_kb is 0. Does this mean that GDS is disabled and if so, how to enable GDS?

**Comment by fxkamd** [comment]
ROCm currently doesn't use GDS for anything. There is no way to enable its use.
