### ISSUE TITLE
Problems using with Navy flounder

### ISSUE THREAD

**Issue by nixx** [RadeonOpenCompute/ROCT-Thunk-Interface#69]
Running software such as rocminfo, results in a assertion error from line 1096 in topology.c, and pretty much nothing is working as expected. This also happens with other tools like clinfo. 

Looking at  the code path, and there is a lookup in gfxip_table_table in which Navy flounder is not defined. Navy Flounder is defined in libhsakmt.h, so it seems like it is added in some parts of the code.

I presume it is a bug?

**Comment by fxkamd** [comment]
Maybe an oversight. I see that Navi Flounder is in the table for the next release, ROCm 4.2, which is going through QA now.

**Comment by kentrussell** [comment]
Cleaning up old tickets. Navy Flounder support is in thunk as of 4.2
