### ISSUE TITLE
pci/pci.h not found

### ISSUE THREAD

**Issue by Dekken** [RadeonOpenCompute/ROCT-Thunk-Interface#7]
It exists in the kernel headers, please consider adding a Cmake argument to specify as I have installed the kernel from source and have it located /kern/rocm/

**Comment by Dekken** [comment]
Modifying the CMakeLists.txt to add $KERN/drivers results in the [following](https://gist.githubusercontent.com/Dekken/28107f8addf2c35b40d5ddff3176d1c3/raw/1599c9b61d35cf71098c67135bf44243445de306/gistfile1.txt)

**Comment by Dekken** [comment]
[This commit](https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/commit/9ff5bd76399cea6e4592b8cb608b11d7256f5914#diff-af6e570e12d8dbd51eeb1c6668bd52a2)

**Comment by fxkamd** [comment]
This header doesn't come from the kernel. It's from libpci. The headers should normally be located in /usr/include/pci/pci.h, so no special include path should be needed. That said, we could probably use pkg-config to get the location in case it's not the standard location.

**Comment by Dekken** [comment]
I see, the only file to return from "locate pci/pci.h" was in the ROCM kernel, so I had presumed it was that. I will see if I can install libpci and try again.

**Comment by Dekken** [comment]
Installing libpci-dev has resolved this.
