### ISSUE TITLE
Why look for libudev?

### ISSUE THREAD

**Issue by haampie** [RadeonOpenCompute/ROCT-Thunk-Interface#72]
Any particular reason why 

https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/blob/3277d5354ed623598a5cea82cc3790a577af177c/CMakeLists.txt#L195

this was added to ROCm 4.5.0? (pinging @kentrussell)

I don't see it being used in the code at all.

It blocks automated builds of this package as reported for instance here https://github.com/spack/spack/issues/28398

**Comment by kentrussell** [comment]
This is a remnant of some old requirements (https://github.com/RadeonOpenCompute/rocminfo/issues/9). With a static thunk and with packaging being more fleshed out, we can remove this change. I have made a change internally and it should be out for our next release (removing zlib and libudev requirements). Thanks for bringing this to our attention!

**Comment by haampie** [comment]
Thanks a lot!

**Comment by kentrussell** [comment]
Sorry for leaving this open so long. Removed as of ROCm 5.3
