### ISSUE TITLE
KFDLocalMemoryTest.Fragmentation segfaults on gfx11

### ISSUE THREAD

**Issue by aaronmondal** [RadeonOpenCompute/ROCT-Thunk-Interface#80]
While trying to get the ROCT-Thunk-Interface running as part of the [rules_ll](https://github.com/eomii/rules_ll) AMDGPU toolchain I found `KFDLocalMemoryTest.Fragmentation` to cause a segfault.

This might be related to certain crashes in mesa (https://gitlab.freedesktop.org/mesa/mesa/-/issues/8225, https://gitlab.freedesktop.org/mesa/mesa/-/issues/7939) as well.

- LLVM commit https://github.com/llvm/llvm-project/commit/a81bdc614a7d79fb9dc54e234b6704f190f588e6
- ROCT-Thunk-Interface at tag rocm-5.4.3 (checked out from github)
- numactl 2.0.16 (from nix store)
- libdrm/libdrm_amdgpu 2.4.114 (from nix store)
- kernel 6.1.8-gentoo

Test failure:

```
[ RUN      ] KFDLocalMemoryTest.Fragmentation
[          ] Found VRAM of 20464MB.
[          ] Trying to allocate 65536 order 0 blocks 
external/rules_ll~override/ROCT-Thunk-Interface/tests/kfdtest/src/KFDTestUtil.cpp:291: Failure
Value of: (hsaKmtAllocMemory(m_Node, m_Size, m_Flags, &m_pBuf))
  Actual: 1
Expected: HSAKMT_STATUS_SUCCESS
Which is: 0
external/rules_ll~override/ROCT-Thunk-Interface/tests/kfdtest/src/KFDTestUtil.cpp:294: Failure
Value of: (hsaKmtMapMemoryToGPUNodes(m_pBuf, m_Size, __null, mapFlags, 1, &m_Node))
  Actual: 1
Expected: HSAKMT_STATUS_SUCCESS
Which is: 0
external/rules_ll~override/ROCT-Thunk-Interface/tests/kfdtest/src/KFDTestUtil.cpp:352: Failure
Expected: ((void *)__null) != (ptr), actual: NULL vs NULL
```

dmesg:

```
kfdtest[1320768]: segfault at 0 ip 00007fa753c61f15 sp 00007ffd39883ea8 error 6 in libc.so.6[7fa753b30000+176000] likely on CPU 14 (core 2, socket 0)
Code: fc ff 0f 1f 00 f3 0f 1e fa 48 89 f8 48 83 fa 20 0f 82 af 00 00 00 c5 fe 6f 06 48 83 fa 40 0f 87 3e 01 00 00 c5 fe 6f 4c 16 e0 <c5> fe 7f 07 c5 fe 7f 4c 17 e0 c5 f8 77 c3 66 66 2e 0f 1f 84 00 00
```

**Comment by fxkamd** [comment]
This test has been blacklisted for a long time. I should not be run automatically when you use run_kfdtest.sh. There is a comment about it in kfdtest.exclude:

> # Fragmentation test fails intermittently on different systems (see KFD-344). It
> # stresses memory management in unusual ways by having lots of memory allocated but
> # not mapped, which is not relevant to compute applications over ROCr.

The test was meant to stress the address space manager that manages the GPU-accessible virtual address aperture. This is no longer in use on current GPUs (since GFXv9) that support the full 48-bit virtual address space and don't need a special aperture with its own address space manager. So this test is pretty meaningless at this point.

**Comment by aaronmondal** [comment]
Cool thanks then this was a false positive :+1:
